# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLab4test():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_lab4test(self):
        self.driver.get("https://tutorialsninja.com/demo/")
        self.driver.set_window_size(1053, 969)
        time.sleep(5)
        self.driver.find_element(By.LINK_TEXT, "Desktops").click()
        time.sleep(5)
        self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
        time.sleep(5)
        assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Mac"
        time.sleep(5)
        self.driver.find_element(By.ID, "input-sort").click()
        time.sleep(5)
        dropdown = self.driver.find_element(By.ID, "input-sort")
        time.sleep(2)
        dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
        time.sleep(5)
        self.driver.find_element(By.CSS_SELECTOR, ".button-group > button:nth-child(1)").click()
        time.sleep(2)
        self.driver.find_element(By.NAME, "search").click()
        time.sleep(2)
        self.driver.find_element(By.NAME, "search").send_keys("Monitors")
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".fa-search").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "input-search").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "description").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "button-search").click()

