# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDay15Q1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_day15Q1(self):
        self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        time.sleep(10)
        self.driver.set_window_size(1054, 968)
        time.sleep(10)
        self.driver.find_element(By.NAME, "username").send_keys("Admin")
        time.sleep(5)
        self.driver.find_element(By.NAME, "password").click()
        time.sleep(5)
        self.driver.find_element(By.NAME, "password").send_keys("admin123")
        time.sleep(5)
        self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
        time.sleep(10)
        assert self.driver.find_element(By.CSS_SELECTOR, "h6").text == "Dashboard"

